import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ModalProvider } from "@/context/ModalContext";
import { AuthProvider } from "@/context/AuthContext";
import { ProjectsProvider } from "@/context/ProjectsContext";
import MotionProvider from "@/components/MotionProvider";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <MotionProvider>
          <AuthProvider>
            <ProjectsProvider>
              <ModalProvider>
                {children}
              </ModalProvider>
            </ProjectsProvider>
          </AuthProvider>
        </MotionProvider>
      </body>
    </html>
  );
}
